---
- name: Register if .env file is present
  stat:
    path: "{{ freescout_basedir }}/.env"
  register: freescout_envfile_present

- name: Copy .env.example to .env
  become: yes
  become_user: "{{ freescout_user }}"
  copy: 
    src: "{{ freescout_basedir }}/.env.example"
    dest: "{{ freescout_basedir }}/.env"
    mode: "0600"
    remote_src: true
  when: not freescout_envfile_present.stat.exists

- name: Apply conffiguration parameters to .env
  become: yes
  become_user: "{{ freescout_user }}"
  lineinfile:
    path: "{{ freescout_basedir }}/.env"
    regexp: "{{ item.name | upper }}="
    line: "{{item.name | upper}}={{ item.value }}"
  with_items: "{{ freescout_config }}"

- name: Generate app key
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan key:generate"
    chdir: "{{ freescout_basedir }}"
  when: not freescout_envfile_present.stat.exists

- name: Link storage
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan storage:link"
    chdir: "{{ freescout_basedir }}"

- name: Migrate database
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan migrate -n --force"
    chdir: "{{ freescout_basedir }}"

- name: Clear freescout cache
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan migrate -n --force"
    chdir: "{{ freescout_basedir }}"

- name: Restart freescout queue
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan queue:restart"
    chdir: "{{ freescout_basedir }}"

- name: Create admin user
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "php artisan freescout:create-user -n --email={{ freescout_admin_user.email }} --firstName={{ freescout_admin_user.firstName }} --lastName={{ freescout_admin_user.lastName }} --password={{ freescout_admin_user.password }} --role=admin"
    chdir: "{{ freescout_basedir }}"
  when: not freescout_envfile_present.stat.exists or freescout_admin_user_force

- name: Install cronjob
  cron:
    name: "Freescout run schedule"
    job: "php {{ freescout_basedir }}/artisan schedule:run > /dev/null 2>&1"
    user: "{{ freescout_user }}"
