---
- name: Clear freescout cache
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "{{ freescout_php_path }} artisan freescout:clear-cache"
    chdir: "{{ freescout_basedir }}"
- name: freescout after-app-update
  become: yes
  become_user: "{{ freescout_user }}"
  command:
    cmd: "{{ freescout_php_path }} artisan freescout:after-app-update"
    chdir: "{{ freescout_basedir }}"
